"""Generate ``web/tokens.css`` from ``obsauto/design_v3.py``.

The whole point of design_v3.py is that a v3 number lives in exactly one place.
That rule does not get weaker because the renderer changed - it gets *easier*,
because CSS can express the alphas natively instead of compositing them to flat
hex the way ``dv.over()`` has to for a ``tk.Canvas`` with no alpha channel.

So: no hand-typed hex in the stylesheets. Run this, commit the output.

    python spike/gen_tokens.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from obsauto import design_v3 as dv

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web", "tokens.css")


def rgb_triplet(hex_value):
    """'#8B7CF6' -> '139 124 246'.

    SPACE separated, not comma. `rgb()` only accepts the `/ alpha` form with
    space-separated components - `rgb(139, 124, 246 / .34)` is a parse error and
    the declaration is dropped in silence, which is how the first run of the
    spike came out with no card surfaces and an invisible aurora.
    """
    return " ".join(str(c) for c in dv._hex_to_rgb(hex_value))


MARK_PNG = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web", "mark.png")


def write_mark_png(size=64):
    """Render the app icon into ``web/mark.png`` for the titlebar.

    The titlebar mark was a plain accent dot, which lost the icon entirely. The
    icon has exactly one source - ``icon_art.render_frame`` - and it is the same
    art the .ico is built from, so generate it here rather than committing a
    second copy that can drift.

    64px: the mark renders at 18 CSS px, so this is ~2x for a 150% display and
    still tiny on disk. It is a bundled read-only asset, so it must also be
    listed in ``nebula-v4.spec`` or the packaged build loses it.
    """
    from obsauto import icon_art
    os.makedirs(os.path.dirname(MARK_PNG), exist_ok=True)
    icon_art.generate_static_icon(size=size).save(MARK_PNG, format="PNG")
    print("wrote %s (%dx%d)" % (MARK_PNG, size, size))


def main():
    L = []
    add = L.append

    add("/* GENERATED by spike/gen_tokens.py from obsauto/design_v3.py.")
    add(" * Do not edit. Change the Python and re-run. */")
    add(":root {")

    add("  /* --- colour ------------------------------------------------ */")
    for name, value in dv.COLORS.items():
        add("  --%s: %s;" % (name.replace("_", "-"), value))
    # Not in COLORS (it is the outer stop of the ground gradient, not a
    # surface), but the stylesheet needs it by name.
    add("  --ground-deep: %s;" % dv.GROUND_DEEP)
    # Triplets for the layers that need real alpha.
    for name in ("ground", "accent", "ember", "card_core", "panel"):
        add("  --%s-rgb: %s;" % (name.replace("_", "-"), rgb_triplet(dv.COLORS[name])))
    add("  --hairline-rgb: %s;" % " ".join(str(c) for c in dv.HAIRLINE_RGB))
    add("  --hairline-a: %s;" % (sum(dv.HAIRLINE_ALPHA) / 2.0))
    add("  --shell-fill-a: %s;" % dv.SHELL_FILL_ALPHA)
    add("  --shell-border-a: %s;" % dv.SHELL_BORDER_ALPHA)
    add("  --core-a: %s;" % dv.CORE_ALPHA)
    add("  --chrome-a: %s;" % round(dv.CHROME_ALPHA / 255.0, 3))

    add("")
    add("  /* --- geometry ---------------------------------------------- */")
    add("  --win-w: %dpx;" % dv.WIDTH)
    add("  --win-h: %dpx;" % dv.HEIGHT)
    add("  --tray-inset: %dpx;" % dv.TRAY_INSET)
    add("  --r-tray: %dpx;" % dv.RADIUS_TRAY)
    add("  --r-core: %dpx;" % dv.RADIUS_CORE)
    add("  --r-card: %dpx;" % dv.RADIUS_CARD)
    add("  --r-tile: %dpx;" % dv.RADIUS_TILE)
    add("  --r-control: %dpx;" % dv.RADIUS_CONTROL)
    add("  --titlebar-h: %dpx;" % dv.TITLEBAR_H)
    add("  --titlebar-pad-l: %dpx;" % dv.TITLEBAR_PAD_LEFT)
    add("  --titlebar-pad-r: %dpx;" % dv.TITLEBAR_PAD_RIGHT)
    add("  --rail-w: %dpx;" % dv.RAIL_W)
    add("  --rail-pad-x: %dpx;" % dv.RAIL_PAD_X)
    add("  --rail-pad-y: %dpx;" % dv.RAIL_PAD_Y)
    add("  --rail-item-h: %dpx;" % dv.RAIL_ITEM_H)
    add("  --rail-item-gap: %dpx;" % dv.RAIL_ITEM_GAP)
    add("  --pane-header-h: %dpx;" % dv.PANE_HEADER_H)
    add("  --pane-header-pad-x: %dpx;" % dv.PANE_HEADER_PAD_X)
    add("  --content-pad: %dpx;" % dv.CONTENT_PAD)
    add("  --stack-gap: %dpx;" % dv.STACK_GAP)
    add("  --pill-h: %dpx;" % dv.CONTROL_PILL_H)
    add("  --field-h: %dpx;" % dv.CONTROL_FIELD_H)
    add("  --sibling-gap: %dpx;" % dv.SIBLING_GAP)
    add("  --rule-fade: %dpx;" % dv.RULE_FADE[0])

    # 6.2's nesting table. inner = outer - padding, asserted in test_design_v3.
    add("")
    add("  /* --- card layers (6.2: shell / padding / core) -------------- */")
    for kind, (shell, pad, core) in dv.CARD_LAYERS.items():
        add("  --%s-shell-r: %dpx;" % (kind, shell))
        add("  --%s-pad: %dpx;" % (kind, pad))
        add("  --%s-core-r: %dpx;" % (kind, core))

    add("")
    add("  /* --- type --------------------------------------------------- */")
    # The Tk font-stack gymnastics in design_v3 exist because Tk truncates
    # family names at 31 chars and cannot see optical sizes. A webview asks for
    # the family by name and lets the OS pick the optical size itself.
    add("  --font-ui: '%s', 'Segoe UI', system-ui, sans-serif;" % dv.FONT_UI)
    add("  --font-mono: '%s', Consolas, monospace;" % dv.FONT_MONO)
    for role, spec in dv.TYPE.items():
        r = role.replace("_", "-")
        add("  --t-%s-size: %spx;" % (r, spec["size"]))
        add("  --t-%s-weight: %d;" % (r, spec["weight"]))
        add("  --t-%s-track: %sem;" % (r, spec["tracking"]))

    add("")
    add("  /* --- motion & states ---------------------------------------- */")
    # These were in design_v3.py from the start (EASING, HOVER_MS, PRESS_MS,
    # PANE_CHANGE_*, LIVE_DOT_*, FOCUS_RING_*, DISABLED_OPACITY) and the first
    # cut of this generator simply did not emit them, so the stylesheet invented
    # ".16s ease" everywhere instead. They are the difference between "the
    # layout is right" and "it feels expensive", and nothing in a static
    # screenshot can catch their absence. Emit them, then use them.
    add("  --ease: cubic-bezier(%s, %s, %s, %s);" % dv.EASING)
    add("  --hover-ms: %dms;" % dv.HOVER_MS)
    add("  --press-ms: %dms;" % dv.PRESS_MS)
    add("  --press-scale: %s;" % dv.PRESS_SCALE)
    add("  --pane-change-ms: %dms;" % dv.PANE_CHANGE_MS)
    add("  --pane-change-rise: %dpx;" % dv.PANE_CHANGE_RISE)
    add("  --live-dot-ms: %dms;" % dv.LIVE_DOT_PERIOD_MS)
    add("  --live-dot-a-min: %s;" % dv.LIVE_DOT_OPACITY[0])
    add("  --live-dot-a-max: %s;" % dv.LIVE_DOT_OPACITY[1])
    add("  --focus-ring-w: %dpx;" % dv.FOCUS_RING_W)
    add("  --focus-ring-offset: %dpx;" % dv.FOCUS_RING_OFFSET)
    add("  --disabled-a: %s;" % dv.DISABLED_OPACITY)

    add("")
    add("  /* --- customise (6.8) ---------------------------------------- */")
    add("  --grid-cols: %d;" % dv.GRID_COLS)
    add("  --grid-gap: %dpx;" % dv.GRID_GAP)
    add("  --handle-strip-h: %dpx;" % dv.HANDLE_STRIP_H)
    add("  --edit-content-a: %s;" % dv.EDIT_CONTENT_OPACITY)
    add("  --grid-overlay-a: %s;" % dv.GRID_OVERLAY_ALPHA)
    add("  --drag-rotate: %sdeg;" % dv.DRAG_ROTATE_DEG)

    add("")
    add("  /* --- background (BACKGROUND) -------------------------------- */")
    bg = dv.BACKGROUND
    add("  --ground-stop: %s%%;" % (bg["ground_stop"] * 100))
    add("  --blob-fade-at: %s%%;" % (bg["blob_fade_at"] * 100))
    for k, v in bg["blob_alpha"].items():
        add("  --blob-a-%s: %s;" % (k, v))
    for k, v in bg["wisp_alpha"].items():
        add("  --wisp-a-%s: %s;" % (k, v))
    add("  --vignette-from: %s%%;" % (bg["vignette"]["transparent_to"] * 100))
    add("  --vignette-a: %s;" % bg["vignette"]["black_alpha"])
    add("  --star-far-opacity: %s;" % bg["star_far_opacity"])

    add("")
    add("  /* --- motion (BACKGROUND_MOTION_UNUSED) ----------------------- */")
    add("  /* Quarantined on tk.Canvas: any mutation forced a full-window")
    add("   * composite, measured p50 110ms at 95%% CPU. On a compositor these")
    add("   * are transform/opacity keyframes and never touch the main thread. */")
    m = dv.BACKGROUND_MOTION_UNUSED
    add("  --blob-cycle-min: %ss;" % m["blob_cycle_s"][0])
    add("  --blob-cycle-max: %ss;" % m["blob_cycle_s"][1])
    add("  --blob-travel: %s%%;" % m["blob_travel_pct"])
    add("  --blob-scale-max: %s;" % m["blob_scale"][1])
    add("  --star-speed-near: %ss;" % m["star_speed_near_s"][0])
    add("  --star-speed-far: %ss;" % m["star_speed_far_s"][0])
    add("  --spotlight-px: %dpx;" % m["pointer_spotlight_px"])
    add("  --spotlight-a: %s;" % m["pointer_spotlight_alpha"])
    add("  --lean-window: %dpx;" % m["pointer_lean_window_px"])
    add("  --lean-ms: %dms;" % m["pointer_lean_ms"])

    add("")
    add("  /* --- 7e palette ---------------------------------------------- */")
    # vh, not %. A percentage padding resolves against the containing block's
    # WIDTH even when it is padding-top, which put the palette ~100px lower
    # than the spec's "22% top offset" ever meant. See design_v3.py.
    add("  --palette-top: %svh;" % round(dv.PALETTE_TOP_FRACTION * 100, 2))
    add("  --palette-w: %dpx;" % dv.PALETTE_W)

    add("}")

    text = "\n".join(L) + "\n"
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d lines, %d bytes)" % (OUT, len(L), len(text)))

    write_mark_png()

    # The counts that matter for the spike write-up.
    print("  %d colours, %d type roles, %d card kinds, %d motion values"
          % (len(dv.COLORS), len(dv.TYPE), len(dv.CARD_LAYERS), len(m)))


if __name__ == "__main__":
    main()
