# -*- mode: python ; coding: utf-8 -*-
# Single-file v4 build: `pyinstaller nebula-v4.spec` -> dist/Nebula-v4.exe
#
# spike/app.py resolves web assets via dirname(__file__) -> spike/web/, which
# lands in sys._MEIPASS when frozen. User data (config, logs, games.json) goes
# through obsauto/paths.APP_DIR next to the exe — never bundle those.
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

SPIKE_WEB = "spike/web"
web_files = [
    (f"{SPIKE_WEB}/{name}", SPIKE_WEB)
    for name in (
        "index.html",
        "app.css",
        "app.js",
        "tokens.css",
        "toast.html",
        "toast.css",
        "toast.js",
        "overlay.html",
        "overlay.css",
        "overlay.js",
        # Titlebar app icon, generated by spike/gen_tokens.py from icon_art.
        "mark.png",
    )
]

datas = [("nebula_icon.ico", ".")] + web_files
datas += collect_data_files("customtkinter")  # obsauto imports still pull CTk
datas += collect_data_files("pystray")

hiddenimports = [
    "webview",
    "webview.platforms",
    "webview.platforms.edgechromium",
    "pystray",
    "PIL",
    "PIL.Image",
    "psutil",
    "keyboard",
    "websocket",
    # app_icons.extract() imports these inside the function so a machine
    # without pywin32 degrades to monogram tiles rather than failing. That
    # also puts them out of reach of a casual static scan, and win32ui is a
    # compiled extension - a missing one would silently cost every real icon
    # in the Games pane in the packaged build only.
    "win32api",
    "win32con",
    "win32gui",
    "win32ui",
]
hiddenimports += collect_submodules("webview.platforms")

a = Analysis(
    ["spike/app.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["design"],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="Nebula-v4",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=["nebula_icon.ico"],
)
